### ISSUE TITLE
在ts和vue的环境中的一些小问题

### ISSUE THREAD

**Issue by vivinbear** [SimonZhangITer/vue-typescript-dpapp-demo#2]
比如filters和beforeRouteEnter这类型的钩子函数该怎么使用呢? 直接把他们当方法并不能将其作为filters呢,还请大佬指教

**Comment by vivinbear** [comment]
这个了解到了,目前是在@Components({filters:{}})就可以了

**Comment by SimonZhangITer** [comment]
对的 只要是 xxxx: {} 这种对象的形式一般都是在component里面写
